config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/portfolio' => 'pages#portfolio', as: :portfolio
  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact
  resources :posts do
    resources :comments
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, :body, presence: true
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)
        @comment.post_id = params[:post_id]
        @comment.save
        
        redirect_to post_path(@comment.post)
    end
    
    def destroy
        @post = Post.find params[:post_id]
        @comment = @post.comments.find params[:id]
        @comment.destroy
        flash.notice = "Comment Deleted!"
        redirect_to post_path(@post)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:author_name, :body)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
  
  def index
        @posts = Post.all
  end
  
  def about
  end
  
  def contact
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order('created_at DESC')
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        
        if @post.save
            flash.notice = "Post Created!"
            redirect_to posts_path
        else
            render 'new'
        end
    end
    
    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
        @comment.post_id = @post_id
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        flash.notice = "Post Updated!"

        redirect_to posts_path
    end


    def destroy
        Post.find(params[:id]).destroy
        flash.notice = "Post Deleted!"
        
        redirect_to posts_path
        
    end
    
    private
        def post_params
            params.require(:post).permit(:title, :body)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @post, @comment ] do |f| %>
  <p>
    
    <%= f.text_field :author_name, placeholder: "your name", class: "inside" %>
  </p>
  <p>
    
    <%= f.text_area :body, placeholder: "comment", class: "inside body-inside" %>
  </p>
  <p>
    <%= f.submit 'Post', class: 'btn-lg newpost' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,height=device-height initial-scale=1">
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="vendor/assets/javascripts/unslider.js" 'data-turbolinks-track' = true></script>
</head>
<body>
<div class="page-wrap">
<div class="header">
  <div class="container">
    <div class="row">
      
      <div class="col-md-9">
        <ul class="nav">
            <li><%= link_to 'Welcome', root_path %></li>
            <li><%= link_to 'Portfolio', portfolio_path %></li>
            <li><%= link_to 'Blog', posts_path %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
            
        </ul>
      </div>
      
      <div class="col-md-3">
        <p class="flash"><%= flash.notice %></p>
      </div>
      
    </div>
  </div>
</div>


  
<%= yield %>
</div>  
<div class="footer">
	<div class="container">
    <div class="social">
      <ul class="pull-right">
        <li><a href="https://www.facebook.com/sarina.rahman" target="_blank"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABzUlEQVRYhcVXPU4CURCeBL4JBeFn5gh4ACoPYOkBhBNQcQQ7G4knWNbG2gYTCzvrrQylNtZAZ0IBjRa7mAds5M3ycCfZZJt5880337w3Q+RvdW5zH4IIggSKOQQrCFbZfwJBxMI9Iqobzj1gDTqDIIZiycrfPh8USwhiatDZMaFrrDyCYO0beA9I6jsiopotdJM6EEyLBs4BMqUmdbxio4UuFLNQwZ2yzNBC93DmJwjugviLiZqZduFPFr6DYgjBAIIBC78cLEeeJlh5ZMzmNe8gVr718B9te6WtZlI7FOd5NPoAgGC91aIQ3BtVvSaiihO3Wm1WLyrtyiULP3qeEW+c65ZLJnNeuFlDMSwgyCUR1Ynb3C+kZjd9rV4X6QoW7hEEY4PTOytPoHjYqrvwFStPsu/DwGREECQGxDd5wtsqhyAyAEgIgkVIACz8bCjlnCBYBWbgzcDAygbARR5AhCkAxbw0AFkJ/EUYnoHEpNoTAIiKXkRBAGTzY4GrOACA36s4a5343wE4j5H5OT4WwN5zTGQbSAIwsDOQpOY9kkHxtRnBIBiw8pMh+/yRjIhKH0pTQZY6lrtMlLWYOFbiauZaicvprm3W83HI9fwHG8AdPKVFx58AAAAASUVORK5CYII="/></a></li>
        <li><a href="http://sarinarahman.tumblr.com/" target="_blank"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACBUlEQVRYhc1XvWobQRD+4PYbC3NwuZk3sGq7cfo0IU3iWoUhL+CAHyBFcCU/QcLdE6QKmJA3MOQ6ubPBuDcCk8JKIWGwC53skyxLuycpysDCFTfzfTt/OwP4SywqLSozKgsau1T2qeyX3wWVmai0AMQBdudIgiaVOY1/xeTe59DYozJHguYi0A0xaVM58AV+RmSo2wbQCL31FpVndYGnEOkgwZYXtqSyQ+P1ssArYbmWVHbm33wF4FUSszzRoLKzKvBKOM4wLSfE5DjEUJRGe5LKNo2fahBpT7q+GZLtVN4AiAAgSqMPNbwwGCtRKvO6N6hDoCSRj2zEQU1GeQpgc2ECxh6AGKLS8lJSuaLyEMDGWPhSJEy4+3hSHngTUWmBysznZ2fu8+waHopT9y7AmxmoLNZIoACNXU+FczE5ofFrFZAJX4vJyehQ+TsgD7qgsh+YQBdVAnWTsPRA/z8g4B+C5RMoQ+CVhCvyQOFdhjMIvF+AQObfiJ7O5UQV7E4xfOdlazg/BrfiP5O1T+NHMflJ5XdJZd/nbXlsxUD4Y+TMvZ3VjGj85nGR/Ekj9Dk2dt0r9+YF/FhUfs0BHzybmCVwICkNnYrKEZWHTt0XUflB462Hbnsa8381knXw4pi+5qF0GIq1juVVTywxHEGLSUXWuJqNe2O0nPYC3L2U5XRSVrKePwAAmB1zBiIZ4wAAAABJRU5ErkJggg=="/></a></li>
        <li><a href="https://www.instagram.com/sarinart/" target="_blank"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACeUlEQVRYhcWXT24aMRTGv8rzPSF1xAzPIl0SwT779gJkRRdZcB3Ihl4BbpJeIChCSk6QZYRYpwuqhHbBEDlgz3hIoliyxCDb7/f++hmIH6moDKmcUjmn5YrKNZXr4vecyqmoDAGkNc6tGBl6VM5o+Ues/IuZtHykcoYMvbeIboiVCZV/YwUfgGz3TgA06mrdpfLuWMEekFtk6EbJlpac0XL5XsIdtyylJWfVmn+AcBeizBKNkNmpfCrAHmImLZdUPgXOuoMvJsTKL8/iZ1EZo4Usyn/uaCETlTGVzx6Qyb7pe95oVxnXFryvmMrYlx2vUpTKmc/stTVPcULlpti/2VnC5w4qZy/bfEWGlsva6qY4cQRsXhT0BDYtHwGkEJVhIGofjgBo+wCK4DyUoTIEldOjATJ099LqC77iG1KcIEW7CoDKKaic1wbI0aHljWPOG+TohJaXAMxBy1UZQKLJuajci8p9osl3AKDy2nPYdbH+h7P+vBTAcgUq12UARs3F7j80ocjRCVU65OigCd19GzUXFRZY1wfI0AsCZOjVB6hwgQuQaNIHAFouPOZcFC7oRwMULigNQheAyt9FEJ66ELRcIMcpAIjKVQ0LzCvT0AWQbe5eOmnYc0uqqFy6ayMAppWF6ABgC3GVaNJHE4omNNGk72oeC1D0j+Wl2OTmZyjoqqbJzaCImXApLvI6fBmlaJcEanDScoUU7ZjLqOw6HgEAUrRNbgZGzUXUzM1gV4qjruPCTxPPwmdRGb2hIRnFNSTb0aDyNhCt79mS3SLYpn9yU7p1xae25a4lAu44Snidh4kzPvFp9toau8fpYw1zv8vjdH98yPP8P7eWpnHVhMdGAAAAAElFTkSuQmCC"/></a></li>
      </ul>
      <div class="credit pull-right">Icon made by <a href="http://www.elegantthemes.com" title="Elegant Themes">Elegant Themes</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div>
    </div>
	</div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/unslider/2.0.3/js/unslider-min.js"></script> 

<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
    $('*[data-confirm]').click(function(){
        return confirm($(this).attr('data-confirm'));
    });
    });
</script>
<script type="text/javascript">
    $(document).ready(function() {
    $('.banner').unslider({
        autoplay: true,
        speed: 400,
        delay: 3000,
        nav: false,
        dots: false,
        arrows: false,
        fluid: true
        
    });
});
</script>
<script type="text/javascript"> 
    $(function() {
        $('.flash').delay(500).fadeIn('normal', function() {
            $(this).delay(2500).fadeOut('slow');
        });
    });
</script>
</body>
</html>

app/views/pages/about.html.erb
<div class="main">
    <div class="about-background">
    <div class="container about">
        
                <p>I am a Montreal-based visual artist and I am currently learning to code via online tutorials. This website was created with Ruby on Rails. The slideshow in the portfolio page was created using a jQuery-based slider called <a href="http://unslider.com/" target="_blank">Unslider</a>. The inital setup for this site was based on the Portfolio Project in the Ruby on Rails section on <a href="https://www.codecademy.com" target="_blank">Codecademy</a>. For the blog section, I wanted to expand on my newfound knowledge of models and controllers by building a blog from scratch. To do this, I followed two very helpful tutorials found <a href="http://tutorials.jumpstartlab.com/projects/blogger.html" target="_blank">here</a> and <a href="https://www.youtube.com/watch?v=BI_VnnOLSKY" target="_blank">here</a>. After learning some more Ruby on Rails, I'd like to focus on jQuery and move on to using other JavaScript libraries like Node.js and Angular.js. </p>
            
    </div>
    </div>
</div>

app/views/pages/portfolio.html.erb
<div class="main">
        <div class="banner-holder">
            <div class="unslider">
                <div class="banner unslider-horizontal" style="position: relative; overflow: auto;">
                    <ul class="unslider-wrap">
                        <li><img src="https://farm2.staticflickr.com/1700/24865559595_215d44165d_b.jpg"style= "width: 100%; height: 60%;"/></li>
                        <li><img src="https://farm2.staticflickr.com/1619/24747663792_6372a0bfcd_b.jpg" style= "width: 100%; height: 60%; float: left;"/></li>
                        <li><img src="https://farm2.staticflickr.com/1443/24497967909_9cbb7f206d_b.jpg" style= "width: 100%; height: 60%; float: left;"/></li>
                    </ul>
                </div>
            </div>
       </div>
</div>
<div class="supporting">
    <div class="container">
        <div class="row">
            <div class="container">
            <div class="col-md-6">
                <img src="https://farm2.staticflickr.com/1559/24896365951_76f3877108.jpg"/>
            </div>
            <div class="col-md-6">
                <img src="https://farm2.staticflickr.com/1684/24362812073_8b01675c59.jpg"/>
            </div>
            </div>
        </div>
        <div class="row">
            <div class="container">
            <div class="col-md-6">
                <img src="https://farm2.staticflickr.com/1502/24871672192_0ded7bc240.jpg"/>
            </div>
            <div class="col-md-6">
                <img src="https://farm2.staticflickr.com/1454/24871671552_1a4ed6555c.jpg"/>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/welcome.html.erb
<div class="main">
  <div class="jumbotron">
    <div class="container">
      <h1>Hello. My name is <span class="highlight">Sarina Rahman</span> and I draw things and build websites.</h1>
      
      <%= link_to 'View my work', portfolio_path, :class => "btn-lg" %>
    </div>
  </div>
</div>

app/views/posts/_comment.html.erb
<div>
  <h4 class="commenter"><%= comment.author_name %></h4>
  <p><%= simple_format(comment.body, class: "comment") %></p>
  <%= button_to "delete", [comment.post, comment], method: :delete, class: "links" %>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <ul class="errors">
    <% @post.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>

  <p>
     <%= f.text_field :title, placeholder: "title", class: "inside" %>
  </p>
              
  <p>
     <%= f.text_area :body, placeholder: "body", class: "inside body-inside" %>
  </p>
               
  <p onclick="">
     <%= f.submit 'Post', :class => 'btn-lg newpost' %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class="main">
    <div class="container">
        <div class="blog">
	       <%= render partial: 'form' %>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="main">
    <div class="container">
        <div class="blog">
        <div onclick="" class="button-breather">
            <%= link_to 'New Post', new_post_path, :class => "btn-lg newpost" %><br>
        </div>
        
            <% @posts.each do |p| %>
            <div class="eachpost">
                <div class="blogtitle">
                    <div class="row">
                        <div class="col-md-9">
                                <h1><%=link_to p.title, post_path(p) =%></h1>
                                
                        </div>
                        <div class="col-md-3">
                                <p class="date"> <%= p.created_at.strftime("%B, %d, %Y") =%> </p>
                        </div>
                    </div>
                </div>
                <div class="blogbody">
                    <p><%= simple_format(p.body) =%></p>
               
                    <%= link_to "edit", edit_post_path(p), class: "button_to links" %>
                    <%= button_to "delete", post_path(p), method: :delete, data: { confirm: 'Are you sure?' }, class: "links" %>
                    <%= link_to pluralize(p.comments.size, "comment"), post_path(p), class: "button_to links" %>
                </div>
                
            </div> 
            <% end %>
        
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="main">
    <div class="container">
        <div class="blog">
	       <%= render partial: 'form' %>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="main">
<div class="container">    
    <div class="blog">
    <div class="eachpost">
        <div class="blogtitle">
            <h1><%= @post.title %></h1>
        </div>
        <div class="blogbody">
            <p class="date"> <%= @post.created_at.strftime("%B, %d, %Y") =%> </p>
            <p><%= @post.body %></p>
            <%= link_to "edit", edit_post_path(@post), class: "button_to links" %>
            <%= button_to "delete", post_path(@post), method: :delete, data: {confirm: "Really delete the post?"}, class: "links" %>
            <%= link_to "see all posts", posts_path, class: "button_to links" %>
        </div>
        
    </div>
        <%= render partial: 'posts/comment', collection: @post.comments %>
        <%= render partial: 'comments/form' %>    
    </div>
</div>
</div>